# Generated by Django 3.1.6 on 2021-02-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(default='static/uploads/banner-02.jpg', upload_to='static/uploads')),
                ('profile', models.ImageField(default='static/uploads/jithu.jpg.jpg', upload_to='static/uplaods')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/uploads/jithu.jpg.jpg', upload_to='static/uplaods')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/uplaods')),
                ('thump_nail', models.ImageField(upload_to='static/uplaods')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
