# Generated by Django 3.1.4 on 2021-02-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='background',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='profile',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='thump_nail',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
