# Generated by Django 3.1.4 on 2021-02-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210210_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='profile',
            new_name='image',
        ),
    ]
