# Generated by Django 3.1.4 on 2021-02-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210210_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appearance',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
